baseurl = "https://www.darlinghq.org/"
languageCode = "en-us"
title = "Darling"
theme = "darlinghq"

[[menu.main]]
	name = "Install"
	url = "https://wiki.darlinghq.org/build_instructions"
	weight = 1
[[menu.main]]
	name = "Docs"
	url = "https://wiki.darlinghq.org/"
	weight = 2
[[menu.main]]
	name = "Blog"
	url = "http://blog.darlinghq.org"
	weight = 3
[[menu.main]]
	name = "GitHub"
	url = "https://github.com/darlinghq/darling"
	weight = 4
[[menu.main]]
	name = "Discord"
	url = "https://discord.gg/XRD3mQA"
	weight = 5
